import star
import pysex

	

class Image:
	"""
	Represent an individual image.
	"""

	def __init__(self, file, cat=None):
		"""
		
		:param file: Path to the FITS file, or alternatively just a string to identify the image.
		:type file: string
		
		:param cat: Catalog generated by SExtractor
		:type cat: asciidata catalog
		
		"""
		self.file = file
		self.cat = cat
		self.quads = None
		self.transform = None
		
		self.xlim = (0, 100)
		self.ylim = (0, 100)
	
	def makecat(self):
		pass
	
	def makestarlist(self):
		pass
	
	def makequads(self):
		pass
	
	def showstarlist(self, filename=None):
		pass
	
	def showquads(self, filename=None):
		pass
		
		

def run(refcat, cat, refn=200, catn=100):
	"""
	ref is a reference catalog
	cats is a list of catalogs to match to the ref
	-> For each cat in cats, finds a trans to make it match to ref
	"""
	print "Making ref quads"
	refstars = star.sortstarlistbyflux(star.readsexcat(refcat, verbose=False))[:refn]
	refquads = star.makequads(refstars, plot=False)

	print "Making cat quads"
	uknstars = star.sortstarlistbyflux(star.readsexcat(cat, verbose=False))[:catn]
	uknquads = star.makequads(uknstars, plot=False)

	print "Finding cands"
	cands = star.proposecands(uknquads, refquads)
	
	print "Refining"
	for cand in cands:
		trans = star.quadtrans(*cand)
		nident = trans.teststars(uknstars, refstars)
		if nident > 10:
			#print "Match"
			trans.refinestars(uknstars, refstars)
			print trans, "->", nident, "stars"
			break
		

